# Generated by Django 4.1.3 on 2022-11-27 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
        ),
    ]
