# Generated by Django 4.1.3 on 2022-11-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_score_exam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
