# Generated by Django 4.1.3 on 2022-11-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('isActive', models.BooleanField(default=True)),
                ('Password', models.CharField(max_length=75)),
            ],
        ),
    ]
